WebUI/ViewComponents/MenuViewComponent.cs
using Blog.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Blog.WebUI.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IApiClient _apiClient;
        public MenuViewComponent(IApiClient apiClient)
        {
            _apiClient = apiClient;
        }

        public IViewComponentResult Invoke()
        {
            var getCategoriesResult = _apiClient.GetAsync($"{Constants.ApiUri.Category}").Result;
            var getCategoriesResponseModel = new List<CategoryItem>();

            if (getCategoriesResult.IsSuccessStatusCode)
                getCategoriesResponseModel = getCategoriesResult.Content.ReadAsJsonAsync<List<CategoryItem>>().Result.Where(x => x.ParentId == null).ToList();

            return View("Menu", getCategoriesResponseModel);
        } 
    }
}

WebUI/Views/Shared/_AdminLayout.cshtml
@using System.Security.Claims;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/simple-sidebar.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
</head>
<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="sidebar-heading">Hoşgeldin @(((ClaimsIdentity) User.Identity).Claims.FirstOrDefault(x => x.Type == ClaimTypes.Name).Value ?? string.Empty) <form asp-action="Logout"><button type="submit"><a>Çıkış</a></button></form></div>
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Article")" class="list-group-item list-group-item-action bg-light">Makele Ekle</a>
                <a href="@Url.Action("ListArticle")" class="list-group-item list-group-item-action bg-light">Makele Listele</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <div class="container-fluid">
            @RenderBody()
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/blog.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <div class="col-4 text-center">
                    <a class="blog-header-logo text-dark" href="/">Digi Blog</a>
                </div>
            </div>
        </header>


        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </ul>
            </div>
        </nav>

        <div class="container">
            <main role="main" class="pb-3">
                <div class="row">



                    @RenderBody()

                    @*<aside class="col-md-4 blog-sidebar">

                            <div class="p-4">
                                <h4 class="font-italic">Archives</h4>
                                <ol class="list-unstyled mb-0">
                                    <li><a href="#">March 2014</a></li>
                                    <li><a href="#">February 2014</a></li>
                                    <li><a href="#">January 2014</a></li>
                                    <li><a href="#">December 2013</a></li>
                                    <li><a href="#">November 2013</a></li>
                                    <li><a href="#">October 2013</a></li>
                                    <li><a href="#">September 2013</a></li>
                                    <li><a href="#">August 2013</a></li>
                                    <li><a href="#">July 2013</a></li>
                                    <li><a href="#">June 2013</a></li>
                                    <li><a href="#">May 2013</a></li>
                                    <li><a href="#">April 2013</a></li>
                                </ol>
                            </div>

                            <div class="p-4">
                                <h4 class="font-italic">Elsewhere</h4>
                                <ol class="list-unstyled">
                                    <li><a href="#">GitHub</a></li>
                                    <li><a href="#">Twitter</a></li>
                                    <li><a href="#">Facebook</a></li>
                                </ol>
                            </div>
                        </aside>*@
                    <!-- /.blog-sidebar -->

                </div>
            </main>
        </div>

        <footer class="blog-footer">
            <p>Blog template built for <a href="https://getbootstrap.com/">Bootstrap</a> by <a href="https://twitter.com/mdo"></a>.</p>
            <p>
                <a href="#">Back to top</a>
            </p>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
        <style>
            .navbar-nav li:hover > ul.dropdown-menu {
                display: block;
            }

            .dropdown-submenu {
                position: relative;
            }

                .dropdown-submenu > .dropdown-menu {
                    top: 0;
                    left: 100%;
                    margin-top: -6px;
                }

            /* rotate caret on hover */
            .dropdown-menu > li > a:hover:after {
                text-decoration: underline;
                transform: rotate(-90deg);
            }
        </style>
        <script>
            $('.dropdown-menu a.dropdown-toggle').on('click', function (e) {
                if (!$(this).next().hasClass('show')) {
                    $(this).parents('.dropdown-menu').first().find('.show').removeClass('show');
                }
                var $subMenu = $(this).next('.dropdown-menu');
                $subMenu.toggleClass('show');


                $(this).parents('li.nav-item.dropdown.show').on('hidden.bs.dropdown', function (e) {
                    $('.dropdown-submenu .show').removeClass('show');
                });


                return false;
            });
        </script>
</body>
</html>

WebUI/Views/Shared/_MenuPartial.cshtml
@model CategoryItem
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (Model.Children != null && Model.Children.Any())
{
    <li class="nav-item dropdown dropdown-submenu"><a class="dropdown-item" href="@Url.Action("Index", new { catId = @Model.Id })">@Model.Name</a>
        <ul class="dropdown-menu">
            @foreach (var category in Model.Children)
            {
                @Html.Partial("_MenuPartial", category)
            }
        </ul>
    </li>
    
}
else
{

    <li><a class="dropdown-item" href="@Url.Action("Index", new { catId = @Model.Id })">@Model.Name</a></li>

}